### PR TITLE
[lineage-15.0] net/wireguard: add wireguard importer

### PR DESCRIPTION
**Pull request by zx2c4**
WireGuard is a next generation secure VPN tunnel for the Linux kernel. It recently has [gained android support](https://forum.xda-developers.com/android/development/wireguard-rom-integration-t3711635), as written about in [xda news](https://www.xda-developers.com/wireguard-vpn-project-support-android-roms/). This commit merges support for it.

### CODE REVIEW

**Comment by zx2c4** [comment]
Any plans to merge this?

**Comment by desalesouche** [comment]
i merged but 15.0 branch kernel is not ready for O actually. it needs
binder commits
by the way, which y6 do you own? 2015 or 2017? do you compile android for
it? y6 users need you! 😊
i whish you all the best for that new year coming.

2017-12-21 21:54 GMT+01:00 Jason A. Donenfeld <notifications@github.com>:

**Comment by zx2c4** [comment]
An older one -- 2015 I assume. Did they re-release with nicer hardware or something?

**Comment by desalesouche** [comment]
yop. https://www.gsmarena.com/huawei_y6_(2017)-8695.php
are you french? i am. from toulouse.

2017-12-22 15:34 GMT+01:00 Jason A. Donenfeld <notifications@github.com>:

**Comment by zx2c4** [comment]
> are you french? i am. from toulouse.

No, but I live in Paris.

**Pull request merged**
